# Generated by Django 5.2.6 on 2026-01-16 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('line_user_id', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('picture_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('status_message', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('last_subscribed_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('is_admin', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='WaterStations',
            fields=[
                ('station_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('station_code', models.CharField(blank=True, max_length=255, null=True)),
                ('station_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('warning_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('critical_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'water_stations',
            },
        ),
        migrations.CreateModel(
            name='WaterLevels',
            fields=[
                ('water_level_id', models.AutoField(primary_key=True, serialize=False)),
                ('water_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rainfall', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_level', models.IntegerField(blank=True, default=0, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('data_source', models.CharField(blank=True, max_length=255, null=True)),
                ('is_processed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.DO_NOTHING, to='pages.waterstations')),
            ],
            options={
                'db_table': 'water_levels',
            },
        ),
    ]
