# Generated by Django 5.2.6 on 2026-01-10 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('line_user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('is_active', models.IntegerField(default=1)),
                ('is_admin', models.IntegerField(default=0)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='WaterStations',
            fields=[
                ('station_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('station_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'water_stations',
            },
        ),
        migrations.CreateModel(
            name='WaterLevels',
            fields=[
                ('water_level_id', models.AutoField(primary_key=True, serialize=False)),
                ('water_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('risk_level', models.IntegerField(blank=True, default=0, null=True)),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.DO_NOTHING, to='pages.waterstations')),
            ],
            options={
                'db_table': 'water_levels',
            },
        ),
    ]
