# Generated by Django 5.2.6 on 2026-01-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='waterlevels',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='waterstations',
            options={'managed': True},
        ),
    ]
